### ISSUE TITLE
Edit Profile 

### ISSUE THREAD

**Issue by hfroese** [hannesmannerheim/qvitter#39]
"Edit Profile" works as long as "$config['site']['qvitter']['timebetweenpolling'] = 5000;"  is set only and returns automatically to "Public Timeline".

**Comment by hannesmannerheim** [comment]
ok, @mmn had the same problem here https://quitter.se/notice/3085174 

my guess is gnu social returns 400 not found on user_timeline.json. qvitter interprets this as the user does not exist and redirects to front page, i.e. public timeline. did you not find the bug that caused user_timeline.json to return 400, @mmn?

**Comment by hannesmannerheim** [comment]
i mean 404, i think

**Comment by hannesmannerheim** [comment]
@hfroese it's probably fixed in gnu social nightly https://quitter.se/notice/3180840

**Comment by hfroese** [comment]
Great. So I'm looking forward to the changes I have to do. I set timebetweenpolling to 20.000 meanwhile.

**Comment by hfroese** [comment]
Works fine after nightly update.

**Comment by mmn** [comment]
Cool. Yeah, this was a GNU social bug rather than a qvitter bug. Thanks for reminding me that it still exists in 1.1.x/master :)
So we can close this issue, right? (I can't do it with my rights in this repo at least)

**Comment by hfroese** [comment]
Yes, you can close this issue :)
